### ISSUE TITLE
Wallcheck

### ISSUE THREAD

**Issue by HEYDARPRO** [ttwizz/Open-Aimbot#111]
whenever i turn on wall check in the game operation siege in roblox the aimbot just stops working what should I do

**Comment by HEYDARPRO** [comment]
also when i export the settings they don't save

**Comment by ttwizz** [comment]
If Wall Check is enabled, the aimbot will not respond to players who are behind a wall or other obstacle. It is recommended to enable it to reduce the risk of detection.

If the settings are not saved when exporting, delete your code executor and download a normal one that has adequate IO Library implementation.

**Comment by ttwizz** [comment]
Open Aimbot does not have any bugs directly related to it at the moment. If you have any problems, then refer to our documentation to find out the subtleties, or just install a normal code executor that does not fake the UNC test.

https://moderka.org/Open-Aimbot/about.html
