### ISSUE TITLE
Silent Aim

### ISSUE THREAD

**Issue by kkt150** [ttwizz/Open-Aimbot#116]
if i chose silent aim dosen´t matter what method but it will crash instantly

i use atlantis executor (98% UNC)

**Comment by ttwizz** [comment]
> if i chose silent aim dosen´t matter what method but it will crash instantly
> 
> i use atlantis executor (98% UNC)

Good afternoon! The problem is known. We will contact you in 1-2 days regarding this situation.

**Comment by kkt150** [comment]
ok

**Comment by ttwizz** [comment]
Unfortunately, we were unable to identify the source of the problem. It is likely that new code executors cannot implement the Hook Library correctly. We apologize for the inconvenience and for the long waiting time
