### ISSUE TITLE
Lag issues stutters

### ISSUE THREAD

**Issue by Dafuuh** [ttwizz/Open-Aimbot#63]
Every second, it keeps dropping by 10 fps, and it's so annoying. It keeps stuttering, and every time I aim, it drops to 40 fps. Turning off notifications helped, and the random aim-part mode is causing the stutters and lag.

**Comment by ttwizz** [comment]
I will check it later. Thanks a lot for reporting

**Comment by DaniHRE** [comment]
Notifications cause this lag as @Dafuuh says.
When i disable the notifications my fps goes up to 200 normally.
When its enabled i have spike lags.

**Comment by ttwizz** [comment]
The reason is starting threads (spawning tasks) in RenderStepped, that notifications create. Probably, the only one way to resolve this issue is remove notifications calls from Aimbot Loop.

**Comment by ttwizz** [comment]
Issue resolved. Thanks for patience
