### ISSUE TITLE
 Add different colors to visible plyer

### ISSUE THREAD

**Issue by DaniHRE** [ttwizz/Open-Aimbot#67]
I think it would be a good idea to have the option to put a different color on the ESP for the player who is visible or not.

In general, the idea here is to implement a mechanism capable of detecting whether the player is visible or not...
Thus providing a better way to legitimately play with Open-Aimbot.

**Comment by ttwizz** [comment]
Hello! It's quite a good idea. I will think about adding it in Visuals tab. But I would advise you to use "Smart ESP" option: it will highlight only the players who you can target.
