### ISSUE TITLE
Not showing all tabs after saving changes

### ISSUE THREAD

**Issue by lilszaszaboy** [ttwizz/Open-Aimbot#87]
I added some changes to load right after I execute the script, but after I opened it again all of the tabs were gone except Aimbot. I would be fine with it but unfortunately it doesnt work. I used it once or twice before I saved the changes. It worked flawlessly before it.

**Comment by ttwizz** [comment]
> I added some changes to load right after I execute the script, but after I opened it again all of the tabs were gone except Aimbot. I would be fine with it but unfortunately it doesnt work. I used it once or twice before I saved the changes. It worked flawlessly before it.

Hi. Please upload screenshot of F9 Console, it may has thrown some errors.

**Comment by lilszaszaboy** [comment]
![image](https://github.com/user-attachments/assets/34456a29-9eb8-4c78-a0fc-d8a05450c715) there you go, it just keeps repeating.

**Comment by lilszaszaboy** [comment]
![Képernyőkép 2024-08-11 192035](https://github.com/user-attachments/assets/94242772-3e64-4aac-8ea7-463443df8e55)
thats the console, its just repeats itself over and over.

**Comment by ttwizz** [comment]
> ![Képernyőkép 2024-08-11 192035](https://private-user-images.githubusercontent.com/167466457/356895365-94242772-3e64-4aac-8ea7-463443df8e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTg2NzcsIm5iZiI6MTcyMzM5ODM3NywicGF0aCI6Ii8xNjc0NjY0NTcvMzU2ODk1MzY1LTk0MjQyNzcyLTNlNjQtNGFhYy04ZWE3LTQ2MzQ0M2RmOGU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlZWNiYTNiNmNjYmRiNjdmMGQxNmY4ZDU3MzVlZDZhM2QxZGI4OGM5YTBjM2Q5NDNkZGNhNWE4NTk0Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-QaQ3k7IqK-gKyjUguZ1F0x4SDh6fYMvFNsBy5mvKw) thats the console, its just repeats itself over and over.

So, what were Aim Key and Trigger Key values?

**Comment by lilszaszaboy** [comment]
> > ![Képernyőkép 2024-08-11 192035](https://private-user-images.githubusercontent.com/167466457/356895365-94242772-3e64-4aac-8ea7-463443df8e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTg2NzcsIm5iZiI6MTcyMzM5ODM3NywicGF0aCI6Ii8xNjc0NjY0NTcvMzU2ODk1MzY1LTk0MjQyNzcyLTNlNjQtNGFhYy04ZWE3LTQ2MzQ0M2RmOGU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlZWNiYTNiNmNjYmRiNjdmMGQxNmY4ZDU3MzVlZDZhM2QxZGI4OGM5YTBjM2Q5NDNkZGNhNWE4NTk0Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-QaQ3k7IqK-gKyjUguZ1F0x4SDh6fYMvFNsBy5mvKw) thats the console, its just repeats itself over and over.
> 
> So, what were Aim Key and Trigger Key values?

Aim key was É , trigger value I think was the same as set.

**Comment by ttwizz** [comment]
> > > ![Képernyőkép 2024-08-11 192035](https://private-user-images.githubusercontent.com/167466457/356895365-94242772-3e64-4aac-8ea7-463443df8e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTg2NzcsIm5iZiI6MTcyMzM5ODM3NywicGF0aCI6Ii8xNjc0NjY0NTcvMzU2ODk1MzY1LTk0MjQyNzcyLTNlNjQtNGFhYy04ZWE3LTQ2MzQ0M2RmOGU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlZWNiYTNiNmNjYmRiNjdmMGQxNmY4ZDU3MzVlZDZhM2QxZGI4OGM5YTBjM2Q5NDNkZGNhNWE4NTk0Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-QaQ3k7IqK-gKyjUguZ1F0x4SDh6fYMvFNsBy5mvKw) thats the console, its just repeats itself over and over.
> > 
> > 
> > So, what were Aim Key and Trigger Key values?
> 
> Aim key was É , trigger value I think was the same as set.

Roblox doesn't support É Keybind, you should try to delete the configuration file and set the key to E or other letter.

**Comment by lilszaszaboy** [comment]
> > > > ![Képernyőkép 2024-08-11 192035](https://private-user-images.githubusercontent.com/167466457/356895365-94242772-3e64-4aac-8ea7-463443df8e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTg2NzcsIm5iZiI6MTcyMzM5ODM3NywicGF0aCI6Ii8xNjc0NjY0NTcvMzU2ODk1MzY1LTk0MjQyNzcyLTNlNjQtNGFhYy04ZWE3LTQ2MzQ0M2RmOGU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlZWNiYTNiNmNjYmRiNjdmMGQxNmY4ZDU3MzVlZDZhM2QxZGI4OGM5YTBjM2Q5NDNkZGNhNWE4NTk0Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-QaQ3k7IqK-gKyjUguZ1F0x4SDh6fYMvFNsBy5mvKw) thats the console, its just repeats itself over and over.
> > > 
> > > 
> > > So, what were Aim Key and Trigger Key values?
> > 
> > 
> > Aim key was É , trigger value I think was the same as set.
> 
> Roblox doesn't support É Keybind, you should try to delete the configuration file and set the key to E or other letter.

Oh i see, where can i delet the config file?

**Comment by ttwizz** [comment]
> > > > > ![Képernyőkép 2024-08-11 192035](https://private-user-images.githubusercontent.com/167466457/356895365-94242772-3e64-4aac-8ea7-463443df8e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTg2NzcsIm5iZiI6MTcyMzM5ODM3NywicGF0aCI6Ii8xNjc0NjY0NTcvMzU2ODk1MzY1LTk0MjQyNzcyLTNlNjQtNGFhYy04ZWE3LTQ2MzQ0M2RmOGU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlZWNiYTNiNmNjYmRiNjdmMGQxNmY4ZDU3MzVlZDZhM2QxZGI4OGM5YTBjM2Q5NDNkZGNhNWE4NTk0Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-QaQ3k7IqK-gKyjUguZ1F0x4SDh6fYMvFNsBy5mvKw) thats the console, its just repeats itself over and over.
> > > > 
> > > > 
> > > > So, what were Aim Key and Trigger Key values?
> > > 
> > > 
> > > Aim key was É , trigger value I think was the same as set.
> > 
> > 
> > Roblox doesn't support É Keybind, you should try to delete the configuration file and set the key to E or other letter.
> 
> Oh i see, where can i delet the config file?

Configuration file is located in "workspace" directory at your executor's folder

**Comment by ttwizz** [comment]
> > > > > > ![Képernyőkép 2024-08-11 192035](https://private-user-images.githubusercontent.com/167466457/356895365-94242772-3e64-4aac-8ea7-463443df8e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTg2NzcsIm5iZiI6MTcyMzM5ODM3NywicGF0aCI6Ii8xNjc0NjY0NTcvMzU2ODk1MzY1LTk0MjQyNzcyLTNlNjQtNGFhYy04ZWE3LTQ2MzQ0M2RmOGU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlZWNiYTNiNmNjYmRiNjdmMGQxNmY4ZDU3MzVlZDZhM2QxZGI4OGM5YTBjM2Q5NDNkZGNhNWE4NTk0Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-QaQ3k7IqK-gKyjUguZ1F0x4SDh6fYMvFNsBy5mvKw) thats the console, its just repeats itself over and over.
> > > > > 
> > > > > 
> > > > > So, what were Aim Key and Trigger Key values?
> > > > 
> > > > 
> > > > Aim key was É , trigger value I think was the same as set.
> > > 
> > > 
> > > Roblox doesn't support É Keybind, you should try to delete the configuration file and set the key to E or other letter.
> > 
> > 
> > Oh i see, where can i delet the config file?
> 
> Configuration file is located in "workspace" directory at your executor's folder

It's name is like 123456789.ttwizz (not UISettings.ttwizz)

**Comment by lilszaszaboy** [comment]
> > > > > > > ![Képernyőkép 2024-08-11 192035](https://private-user-images.githubusercontent.com/167466457/356895365-94242772-3e64-4aac-8ea7-463443df8e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTg2NzcsIm5iZiI6MTcyMzM5ODM3NywicGF0aCI6Ii8xNjc0NjY0NTcvMzU2ODk1MzY1LTk0MjQyNzcyLTNlNjQtNGFhYy04ZWE3LTQ2MzQ0M2RmOGU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlZWNiYTNiNmNjYmRiNjdmMGQxNmY4ZDU3MzVlZDZhM2QxZGI4OGM5YTBjM2Q5NDNkZGNhNWE4NTk0Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-QaQ3k7IqK-gKyjUguZ1F0x4SDh6fYMvFNsBy5mvKw) thats the console, its just repeats itself over and over.
> > > > > > 
> > > > > > 
> > > > > > So, what were Aim Key and Trigger Key values?
> > > > > 
> > > > > 
> > > > > Aim key was É , trigger value I think was the same as set.
> > > > 
> > > > 
> > > > Roblox doesn't support É Keybind, you should try to delete the configuration file and set the key to E or other letter.
> > > 
> > > 
> > > Oh i see, where can i delet the config file?
> > 
> > 
> > Configuration file is located in "workspace" directory at your executor's folder
> 
> It's name is like 123456789.ttwizz (not UISettings.ttwizz)

Yes I got it and its back to normal. thanks for your help.
Btw love your script probably the best one rn.

**Comment by ttwizz** [comment]
> > > > > > > > ![Képernyőkép 2024-08-11 192035](https://private-user-images.githubusercontent.com/167466457/356895365-94242772-3e64-4aac-8ea7-463443df8e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTg2NzcsIm5iZiI6MTcyMzM5ODM3NywicGF0aCI6Ii8xNjc0NjY0NTcvMzU2ODk1MzY1LTk0MjQyNzcyLTNlNjQtNGFhYy04ZWE3LTQ2MzQ0M2RmOGU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTFlZWNiYTNiNmNjYmRiNjdmMGQxNmY4ZDU3MzVlZDZhM2QxZGI4OGM5YTBjM2Q5NDNkZGNhNWE4NTk0Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-QaQ3k7IqK-gKyjUguZ1F0x4SDh6fYMvFNsBy5mvKw) thats the console, its just repeats itself over and over.
> > > > > > > 
> > > > > > > 
> > > > > > > So, what were Aim Key and Trigger Key values?
> > > > > > 
> > > > > > 
> > > > > > Aim key was É , trigger value I think was the same as set.
> > > > > 
> > > > > 
> > > > > Roblox doesn't support É Keybind, you should try to delete the configuration file and set the key to E or other letter.
> > > > 
> > > > 
> > > > Oh i see, where can i delet the config file?
> > > 
> > > 
> > > Configuration file is located in "workspace" directory at your executor's folder
> > 
> > 
> > It's name is like 123456789.ttwizz (not UISettings.ttwizz)
> 
> Yes I got it and its back to normal. thanks for your help. Btw love your script probably the best one rn.

Thank you
